repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: yarn prettier --write --list-different
        files: \.(js|ts)$
        pass_filenames: true
        language: system
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: yarn lint
        pass_filenames: false
        language: system
