name: test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Set up Python for pre-commit
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          # make sure you update the pre-commit version below
          key: ${{ env.pythonLocation }}-pip-pre-commit-2.20.0

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}

      - name: Install yarn packages
        run: |
          yarn --prefer-offline

      - name: Run pre-commit
        run: |
          # make sure you update the pip cache key above
          pip install pre-commit==2.20.0
          pre-commit run --all-files

      - name: run tests
        run: |
          yarn test
          tsc


